#!/usr/bin/env ruby
@pages = %w[index] #%w[index home about services products portfolio contacts]
@locales = []#%w[it en de fr es]


@server_pid = fork do
  exec('./script/server -e caching')
end

sleep 4

@expired_pages = []
@host = ARGV.first || 'localhost:3000'

def self.cache(path)
  full_path = File.join @host, path
  result = system("curl --silent #{full_path} > /dev/null")
  puts "Caching #{full_path}...#{result ? 'ok' : 'ERROR'}"
  @expired_pages << path
end

cache File.join('/clean')

puts "Press ENTER to continue..."
gets

@pages.each do |action|
  @locales.each do |locale|
    cache [page_locale, action+'.html'       ].compact.join('/')
    cache [page_locale, action, 'index.html' ].compact.join('/') unless action == 'index'
  end
  cache action+'.html'
  cache action+'/index.html' unless action == 'index'
end
cache File.join('/stylesheets/all.css')
cache File.join('/javascripts/all.js')


Process.kill 'KILL', @server_pid
Process.wait @server_pid