#!/usr/bin/env ruby
@pages = %w[index home about services products portfolio contacts]
@locales = %w[it en de fr es]


@server_pid = fork do
  exec('./script/server -e caching')
end

sleep 4

@expired_pages = []
@host = ARGV.first || 'localhost:3000'

def self.cache(path)
  full_path = File.join @host, path
  result = system("curl --silent #{full_path} > /dev/null")
  puts "Caching #{full_path}...#{result ? 'ok' : 'ERROR'}"
  @expired_pages << path
end

cache File.join('/clean')
cache File.join('/index.html')

@pages.each do |action|
  @locales.each do |page_locale|
    [ [page_locale, action+'.html'].join('/'),
      [page_locale, action, 'index.html' ].join('/'),
      action+'.html', action+'/index.html'
    ].each do |path|
      cache path
    end
  end
end


Process.kill 'KILL', @server_pid
Process.wait @server_pid